ALTER TABLE "FinanceWeek"
  ADD COLUMN IF NOT EXISTS "month" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "year" INTEGER NOT NULL DEFAULT 2000;

UPDATE "FinanceWeek"
SET
  "month" = EXTRACT(MONTH FROM "startDate"),
  "year" = EXTRACT(YEAR FROM "startDate");

ALTER TABLE "FinanceWeek"
  ALTER COLUMN "month" DROP DEFAULT,
  ALTER COLUMN "year" DROP DEFAULT;
